name: 'tcsm'
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pandas
  - snakemake
  - r-stm
  - r-tm
  - r-clue
  - matplotlib
  - scikit-learn
  - seaborn
  - xlrd
  - r-argparse
